"""Add user_id and soft delete to cached_asm_scans

Revision ID: fb340ee8dabb
Revises: d1cd1f664544
Create Date: 2026-01-03 19:33:45.455717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb340ee8dabb'
down_revision: Union[str, Sequence[str], None] = 'd1cd1f664544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add columns as nullable first
    op.add_column('cached_asm_scans', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('cached_asm_scans', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('cached_asm_scans', sa.Column('is_active', sa.Boolean(), nullable=True))

    # Step 2: Update existing rows with default values
    op.execute("UPDATE cached_asm_scans SET updated_at = scanned_at WHERE updated_at IS NULL")
    op.execute("UPDATE cached_asm_scans SET is_active = 1 WHERE is_active IS NULL")

    # Step 3: Create indexes
    op.create_index(op.f('ix_cached_asm_scans_deleted_at'), 'cached_asm_scans', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cached_asm_scans_user_id'), 'cached_asm_scans', ['user_id'], unique=False)
    # op.create_foreign_key(None, 'cached_asm_scans', 'users', ['user_id'], ['id'], ondelete='SET NULL')  # SQLite doesn't support this


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'cached_asm_scans', type_='foreignkey')  # SQLite doesn't support this
    op.drop_index(op.f('ix_cached_asm_scans_user_id'), table_name='cached_asm_scans')
    op.drop_index(op.f('ix_cached_asm_scans_deleted_at'), table_name='cached_asm_scans')
    op.drop_column('cached_asm_scans', 'is_active')
    op.drop_column('cached_asm_scans', 'deleted_at')
    op.drop_column('cached_asm_scans', 'updated_at')
    # op.drop_column('cached_asm_scans', 'user_id')  # Already exists, don't drop
    # ### end Alembic commands ###
